# Generated by Django 5.1.1 on 2024-10-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_dimensions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='seller',
            field=models.TextField(null=True),
        ),
    ]
