# Generated by Django 5.1.1 on 2024-10-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_productmodel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='state',
        ),
    ]
