# Generated by Django 5.1.1 on 2024-10-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_productmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_dimensions',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='seller',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
