# Generated by Django 5.1.1 on 2024-10-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
